"""Event model and persistence service."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Any, Iterable

from psycopg import Connection
from psycopg.types.json import Jsonb


# language=PostgreSQL
INSERT_EVENT_SQL = """
    INSERT INTO events (
        isin,
        event_type,
        severity,
        event_date,
        description,
        details
    )
    VALUES (%s, %s, %s, %s, %s, %s)
    ON CONFLICT DO NOTHING
"""


@dataclass(frozen=True, slots=True)
class Event:
    """A business event generated by a monitoring rule."""

    isin: str | None
    event_type: str
    severity: str
    event_date: date
    description: str
    details: dict[str, Any] = field(default_factory=dict)


def save_events(connection: Connection, events: Iterable[Event]) -> int:
    """Persist events without duplicating an existing event identity."""

    inserted_count = 0
    with connection.cursor() as cursor:
        for event in events:
            cursor.execute(
                INSERT_EVENT_SQL,
                (
                    event.isin,
                    event.event_type,
                    event.severity,
                    event.event_date,
                    event.description,
                    Jsonb(event.details),
                ),
            )
            inserted_count += max(cursor.rowcount, 0)

    return inserted_count
